server {
    listen 80;

    server_name _;

    root /var/www/html/public;

    index index.php index.html;

    error_log /var/log/nginx/error.log; # log errors to a file
    access_log /var/log/nginx/access.log; # log access requests to a file

    server_tokens off; # hide nginx version
    add_header X-Frame-Options "SAMEORIGIN"; # prevent clickjacking
    add_header X-XSS-Protection "1; mode=block"; # prevent XSS attacks
    add_header X-Content-Type-Options "nosniff"; # prevent MIME type sniffing

    gzip on; # enable gzip compression
    gzip_vary on; # enable gzip compression for all requests
    gzip_min_length 1024; # only compress files larger than 1KB
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript; # compress these file types

    client_max_body_size 1024M; # increase max upload size

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404; # return 404 if the file doesn't exist
        fastcgi_split_path_info ^(.+\.php)(/.+)$; # split the path info for PHP files
        fastcgi_pass app:9000; # pass the request to the PHP-FPM container
        fastcgi_index index.php; # set the default index file

        include fastcgi_params; # include the default fastcgi parameters
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; # set the script filename
        fastcgi_param PATH_INFO $fastcgi_path_info; # set the path info

        fastcgi_read_timeout 60s; # increase the read timeout for PHP-FPM
    }

    location ~ /\.ht {
        deny all; # deny access to .htaccess files
    }

    # Cache static files for a long time
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires max;
        log_not_found off; # don't log 404 errors for static files
        access_log off; # don't log access requests for static files
    }
}
